### ISSUE TITLE
Download links broken again

### ISSUE THREAD

**Issue by djoveryde** [BuiltBrokenModding/ICBM#62]
Cannot download any files. Even removing the last part doesn't work anymore :(

Ps great work so far guys!

**Comment by djoveryde** [comment]
Managed to work around it again, not sure why it didnt work earlier.

**Comment by DarkGuardsman** [comment]
I see what is wrong the site thinks the links are internal links

**Comment by DarkGuardsman** [comment]
Too add to that the file names changed in the buildscript, i'll have to recode the plugin to account for these changes.

**Comment by djoveryde** [comment]
Seems it's changed now, the icbm download folder is showing a list of voltz engine.rar files instead

**Comment by DarkGuardsman** [comment]
Ya when i updated the plugin i forgot to tell dmod the config folder changed. We should have it fixed shortly

**Comment by DWildwolf** [comment]
There is still an issue with the download links, at least for me. When I get past the adfly thing I just get the 404 not found message.

**Comment by DarkGuardsman** [comment]
Ya seems like i fix one issue and create another. This time the plugin forgot a / between the file name and link. I'll fix it here later today but you should be able to use the link bellow the downloads to access the maven. In which all the downloads are located. http://ci.builtbroken.com/maven/dev/builtbroken/
